# -*- coding: utf-8 -*-
"""Task1_Econom_cities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dScFRiwG3KfdmomtW-DfQQ_zBXYMnnel
"""

# Commented out IPython magic to ensure Python compatibility.
#  Активируем библиотеки

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
# %matplotlib inline

import os

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn import preprocessing

url = "https://raw.githubusercontent.com/Olga225/ITMO_Data_Analysis/refs/heads/main/Econom_Cities_data.csv"
df = pd.read_csv(url, sep=";", index_col='City')

"""В наборе данных два столбца Prace и Salary подразумеваются как числовые (проценты), однако записаны как строки формата 'x,f', что требует корректировки и приведения типов.

Также посмотрим общие характеристики данных и полный набор данных, т.к. его размер относительно невелик.
"""

df['Price'] = (df['Price'].apply(lambda x: x.replace(',','.'))).astype(float)
df['Salary'] = (df['Salary'].apply(lambda x: x.replace(',','.'))).astype(float)

print(df.describe())
print(df.head())

print(df)

"""Из полученной информации видно, что в двух строках в столбцах Work и Salary присутствуют, вероятно, пропуски, замененные на -9999.

Построим графики распределения Work, Price и Salary до и после удаления строк с пропущенными зачениями.
"""

figure, axis = plt.subplots(3, 2, figsize=(10, 10))

axis[0, 0].hist(df['Work'], edgecolor = 'black')
axis[0, 1].hist(df[df['Work'] > -9999]['Work'], edgecolor = 'black')

axis[1, 0].hist(df['Salary'], edgecolor = 'black', color = 'green')
axis[1, 1].hist(df[df['Salary'] > -9999]['Salary'], edgecolor = 'black', color = 'green')

axis[2, 0].hist(df['Price'], edgecolor = 'black', color = 'blue')

print(f"Пропущенных значений в Work: {len(df[df['Work'] <= -9999])}, {round(len(df[df['Work'] <= -9999]) / len(df), 3) * 100}%")
print(f"Пропущенных значений в Salary: {len(df[df['Salary'] <= -9999])}, {round(len(df[df['Salary'] <= -9999]) / len(df), 3) * 100}%")

"""После удаления пропущенных значений оценим вновь характеристики набор данных."""

df = df[(df['Work'] > -9999) & (df['Salary'] > -9999)]
print(df.describe())

"""Проведем нормировку данных."""

stand_1 = preprocessing.StandardScaler()
#stand_1 = preprocessing.MaxAbsScaler()
#stand_1 = preprocessing.MinMaxScaler()

stand_1.fit(df)
X = stand_1.transform(df)
X = pd.DataFrame(X, index=df.index, columns=df.columns)

print(X.head())

"""Проведем кластеризацию.


"""

link = linkage(X, 'ward', 'euclidean')
print(type(link))
print(link.shape)

print(link[:15])

"""Построим дендрограмму"""

fig = plt.figure(figsize=(8,6))
dn = dendrogram(link, labels= df.index.tolist())

"""Посмотрим "каменистую осыпь"."""

dist = link[:, 2]
dist

dist_rev = dist[::-1]
idxs = range(1, len(dist) + 1)
plt.plot(idxs, dist_rev, marker='o')
plt.title('Расстояние между объединяемыми кластерами')
plt.xlabel('Шаг объединения')
plt.ylabel('Расстояние')

plt.yticks(np.arange(min(dist[::-1]), max(dist[::-1])+1, 0.5))

plt.show()

"""Определим "порог" расстояния в 4 согласно полученной информации."""

h = 4

fig = plt.figure(figsize=(9,7))

dn = dendrogram(link, color_threshold = h, labels=df.index.tolist())

"""Таким образом, получаем 4 кластера. Добавим столбец кластера в набор данных и оценим содержимое согласное по средним значениям столбцов."""

df['cluster'] = fcluster(link, h, criterion='distance')

print(df.sort_values(by = 'cluster'))

df.describe()

df.groupby('cluster').mean()

"""Интерпретация:

**Кластер 1.** Экономические центры. Умеренное среднее время работы, очень высокие ценами и высокие зарплатами. Скорее всего, представляют собой дорогие для жизни города с высоким уровнем жизни.

**Кластер 2.** Развитые города. Умеренное среднее время работы, высокие цены и зарплаты: ниже, чем в первом кластере, но выше медианных. Вероятно, обладают сильной сбалансированной экономикой.

**Кластер 3.** Развивающиеся города. Умеренное среднее время работы, умеренные цены и невысокие зарплаты. Скорее всего, обладают активно растущей экономикой, на что указывает несбалансированный индекс цен и запрлат.

**Кластер 4.** Города с экономическими проблемами. Очень высокое среднее время работы, низкие цены и зарплаты. Скорее всего, имеют несбалансированную экономику и худшее качество жизни по сравнению с остальными кластерами.
"""