# -*- coding: utf-8 -*-
"""Task1_Леденцы.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QV9GX4yZM_uor4VqOTlEyBewzFjQVRQg
"""

# Commented out IPython magic to ensure Python compatibility.
#  Активируем библиотеки

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
# %matplotlib inline

import os
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

url = "https://raw.githubusercontent.com/Olga225/ITMO_Data_Analysis/refs/heads/main/Lollipops.dat"
df = pd.read_csv(url, sep=";")

"""Просмотрим основную информацию о наборе данных и первые строки."""

print(df.describe())
print(df.head())

"""Проведем кластеризацию."""

link = linkage(df, 'ward', 'euclidean')
print(type(link))
print(link[:15])

"""Построим дендрограмму."""

dn = dendrogram(link,
                labels=df.index.tolist(),
                leaf_font_size = 10,
                truncate_mode='lastp',
                orientation = "right",
                leaf_rotation=0.)

"""Оценим расстояние между кластерами методом "каменистой осыпи". В данных много объектов с нудевым расстояниям между ними - для удобства интерпретации построим график без их учета."""

dist = link[:, 2]
dist_rev = dist[::-1]
idxs = range(1, len(dist) + 1)
plt.plot(idxs, dist_rev, marker='o', markersize=2)
plt.title('Расстояние между объединяемыми кластерами')
plt.xlabel('Шаг объединения')
plt.ylabel('Расстояние')

dist = link[:, 2]
dist_rev = list(filter(lambda x: x != 0, dist[::-1]))
idxs = range(1, len(dist_rev) + 1)
plt.plot(idxs, dist_rev, marker='o', markersize=2)
plt.yticks(np.arange(min(dist_rev[::-1]), max(dist_rev[::-1])+1, 2))
plt.title('Расстояние между объединяемыми кластерами')
plt.xlabel('Шаг объединения')
plt.ylabel('Расстояние')

"""Излом происходит после расстояния 13.15. Установим порог по результатам анализа дендрограммы и "каменистой осыпи"."""

h = 14

dn = dendrogram(link,
                labels=df.index.tolist(),
                leaf_font_size = 10,
                truncate_mode='lastp',
                orientation = "right",
                leaf_rotation=0.,
                color_threshold = h)

"""Добавим в набор данных информацию о кластерах."""

df['cluster'] = fcluster(link, h, criterion='distance')

print(df.head())

df.groupby('cluster').size()

"""Посмотрим средние значения признаков для каждого кластера."""

df.groupby('cluster').mean()

"""Интерпретация:

**Кластер 1.** Люди, которые считают леденцы полезными для здоровья.

Их оценки по всем вопросам, кроме V9, V10 и V11 (связаны со снятием различных симптомов болезни), близки к медианным (3.0), а по V9, V10 и V11 повышены почти до макисмального (5.0). Скорее всего, люди данной категории воспринимают леденцы как способ облегчить симптоматику плохого самочувствия.

**Кластер 2.** Люди, которые используют леденцы как способ справиться с запахом изо рта.

Их оценки по всем вопросам, кроме V1-V4 (связаны с освежением дыхания и повышением уверенности), близки к медианным, а по V1-V4 повышены почти до макисмального. Скорее всего, люди данной категории едят леденцы чтобы ощутить свежесть дыхания.

**Кластер 3.** Люди, которые используют леденцы для концентрации.

Их оценки по всем вопросам, кроме V7 и V8 (связаны с концентрацией), близки к медианным, а по V7 и V8 повышены почти до макисмального. Скорее всего, люди данной категории едят леденцы чтобы отвлечься и сконцентрироваться на задаче.


**Кластер 4.** Люди, которым следят за питанием.

Их оценки по всем вопросам, кроме V5 и V6 (связаны с вкусовым эффектом), близки к медианным, а по V5 и V6 повышены почти до макисмального. Скорее всего, люди данной категории едят леденцы, чтобы преодолеть желание сладкого и как заменитель "вредной" еды.
"""